image: "docker-registry.default.svc:5000/miq-build/ruby-psql:latest"

variables:
  POSTGRES_DB: vmdb_test
  POSTGRES_USER: postgres
  #POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  GIT_CRED: gitlab-ci-token:${CI_JOB_TOKEN}@git.icdc.io
  RAILS_ENV: test
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: 300000
  RUBY_GC_HEAP_INIT_SLOTS: 600000
  RUBY_GC_HEAP_GROWTH_FACTOR: '1.25'
  PARALLEL_TEST_PROCESSORS: 2

services:
  - postgres:9.5

before_script:
  - source ${CI_PROJECT_DIR}/tools/ci/before_install.sh
  - bundle install 

  
stages:
  - test

rubocop:
  stage: test
  tags: [icdc-g]
  script:
    - (git diff HEAD --name-only --diff-filter=MA  & git diff HEAD~1 --name-only --diff-filter=MA;) | sort | uniq | xargs bundle exec rubocop

brakeman:
  stage: test
  tags: [icdc-g]
  script:
    - bundle exec rake test:brakeman:setup
    - bundle exec rake test:brakeman

#vmdb:
#  stage: test
#  tags: [icdc-g]
#  script:
#    - export PARALLEL=true
#    - bundle exec rake test:vmdb:setup
    #- bundle exec rake test:vmdb
