stages:
  - code_audit
#  - rubocop

variables:
  # Can be overriden in project/group CI/CD settings
  # BASE_REGISTRY: "artifactory.icz.icdc.io/icdc-docker-proxy"
  # CI_REGISTRY: "artifactory.icz.icdc.io/sys-docker"
  # GITLEAKS_IMAGE: "ghcr.io/gitleaks/gitleaks:latest"
  # SERVICE_GROUP: compute
  IMAGE_NAME: "$CI_REGISTRY/$SERVICE_GROUP/$CI_PROJECT_NAME:latest"

  # Outdated variables:
  POSTGRES_DB: vmdb_test
  POSTGRES_USER: postgres
  #POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  GIT_CRED: os-deploy:${CI_JOB_TOKEN}@git.zby.icdc.io
  RAILS_ENV: test
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: 300000
  RUBY_GC_HEAP_INIT_SLOTS: 600000
  RUBY_GC_HEAP_GROWTH_FACTOR: '1.25'
  PARALLEL_TEST_PROCESSORS: 2

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
    - if: $CI_COMMIT_BRANCH == "dev"

#services:
#  - postgres

gitleaks:
  stage: code_audit
  tags:
    - testing
  variables:
    CONTAINER_NAME: "${CI_PROJECT_NAME}-gitleaks"
  before_script:
    - podman stop "${CONTAINER_NAME}" || true
  script:
    - >
      podman run --rm
      -v "$(pwd):/repo:Z" -w /repo
      "$GITLEAKS_IMAGE" git
      --redact
      --no-banner
      /repo
      --report-format json
      --report-path /repo/gitleaks.json
  artifacts:
    when: always
    paths:
      - gitleaks.json
    reports:
      secret_detection: gitleaks.json

rubocop:
  image: "ahrechushkin/ruby-postgresql"
  stage: rubocop
  tags: [icdc_j]
  before_script:
    - bundle update && bundle install 
  script:
    - gem install rubocop
    - (git diff HEAD --name-only --diff-filter=MA  & git diff HEAD~1 --name-only --diff-filter=MA;) | sort | uniq | sed -e '/Gemfile/d' -e '/gitlab-ci/d' -e 'rubocop' | xargs rubocop

#brakeman:
#  stage: test
#  tags: [icdc_j]
#  script:
#    - bundle exec rake test:brakeman:setup
#    - bundle exec rake test:brakeman

#vmdb:
#  stage: test
#  tags: [icdc-j]
#  script:
#    - export PARALLEL=true
#    - bundle exec rake test:vmdb:setup
#    - bundle exec rake test:vmdb
