resources:
  routers:
  - default
  networks:
  - base:
      mtu: 1500
      subnet: 
        cidr: 10.207.<%= ENV['LOCATION_CODE'] %>.0/24
        dhcp: true
        gateway: 10.207.<%= ENV['LOCATION_CODE'] %>.1
        router: default
