resources:
  routers:
  - default
  networks:
  - base:
      mtu: 1500
      subnet: 
        cidr: 10.207.<%= ENV['LOC_NUMBER'] %>.0/24
        dhcp: true
        gateway: 10.207.<%= ENV['LOC_NUMBER'] %>.1
        router: default
