---
:location:
  1:
    :url: https://zabbix-idc.icdc.io/api_jsonrpc.php
    :login: api_user
    :password: B1gb0sss
  2:
    :url: https://zabbix-nb5.icdc.io/api_jsonrpc.php
    :login: api_user
    :password: B1gb0sss
